Few changes for parallel run 1

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -1,104 +1,142 @@
 name: GitHub Actions Demo
 run-name: ${{ github.actor }} is testing out GitHub Actions
 on: [push]
-  #push:
-  #  branches-ignore:
-  #    - 'main'
+
 jobs:
-  Pylint:
+  pre-commit:
     runs-on: ubuntu-latest
-    continue-on-error: true # To remove
     steps:
-      - name: Check .editorconfig
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
+      - uses: actions/setup-python@v3
+        with:
+          python-version: '3.10'
+          cache: 'pip'
+      - name: Install pre-commit
+        run: |
+          python -m pip install pre-commit
+          pre-commit install
+      - name: Run pre-commit
+        run: pre-commit run --all-files
+
+  editorconfig-check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Check .editorconfig exists
+        run: |
+          if [ ! -f .editorconfig ]; then
+            echo ".editorconfig file not found in root directory"
+            exit 1
+          fi
+      - name: Install editorconfig-checker
+        run: |
+          npm install -g editorconfig-checker
+          editorconfig-checker
+
+  secrets-check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0
+      - name: Check for hardcoded secrets
+        uses: gitleaks/gitleaks-action@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  markdown-check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '22'
+      - name: Install markdownlint
+        run: npm install -g markdownlint-cli
+      - name: Check markdown files
+        run: markdownlint-cli .
+
+  code-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
       - name: Set up Python
         uses: actions/setup-python@v3
         with:
           python-version: '3.10'
           cache: 'pip'
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '22'
-      - name: Check for hardcoded secrets
-        uses: gitleaks/gitleaks-action@v2
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Install dependencies
-        run: |
-            pip install pylint black flake8
-            npm install -g markdownlint-cli editorconfig-checker
-            editorconfig-checker
-      - name: Run unit tests
-        run: |
-            cd app
-            python -m unittest discover -v
+      - name: Install linting tools
+        run: pip install pylint black flake8
       - name: Lint Python code
         run: |
-            find . -name '*.py' | xargs pylint
-            black --check --diff .
-            flake8 .
-      - name: Check markdown files
-        run: markdownlint-cli .
-  docker-build:
-    needs: Pylint
+          find . -name '*.py' | xargs pylint
+          black --check --diff .
+          flake8 .
+
+  unit-tests:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
+      - name: Set up Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: '3.10'
+          cache: 'pip'
+      - name: Run unit tests
+        run: |
+          cd app
+          python -m unittest discover -v
 
+  docker-build:
+    needs: [pre-commit, editorconfig-check, secrets-check, markdown-check, code-lint, unit-tests]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
-
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Build and do not push Docker image
+      - name: Build Docker image
         uses: docker/build-push-action@v2
         with:
           context: .
-          # changed initial 'push: true' to 'false'
-          push: false # we need to check for vulnerabilities first
-
+          push: false
           tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/u34:${{ github.sha }}
             ${{ secrets.DOCKERHUB_USERNAME }}/u34:latest
+
   trivy:
     needs: docker-build
     runs-on: ubuntu-latest
     outputs:
       has_critical_vulnerabilities: ${{ steps.trivy.outputs.exit_code }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
+      - uses: actions/checkout@v2
       - name: Scan Docker image with Trivy
         uses: aquasecurity/trivy-action@master
-        continue-on-error: true # Ignore Trivy scan errors because some of them are in used modules, how to deal?
+        continue-on-error: true
         with:
           image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/u34:${{ github.sha }}
           format: 'table'
           exit-code: '1'
           ignore-unfixed: true
-          severity: 'CRITICAL' #with HIGH it fails in some Ansible Collections within the Docker
+          severity: 'CRITICAL'
+
   push-to-docker:
     needs: trivy
     runs-on: ubuntu-latest
     if: ${{ needs.trivy.outputs.has_critical_vulnerabilities == '0' }}
     steps:
-      - name: Checkout code  # Ensures Dockerfile is available
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-
       - name: Push Docker image
         uses: docker/build-push-action@v2
         with:
@@ -107,29 +145,16 @@ jobs:
           tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/u34:${{ github.sha }}
             ${{ secrets.DOCKERHUB_USERNAME }}/u34:latest
-  #snyk:
-  #  #needs: Pylint
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #    - uses: actions/checkout@v2
-  #    - name: Install Snyk dependencies
-  #      run: pip install -r requirements.txt
-  #    - name: Run Snyk to check for vulnerabilities
-  #      uses: snyk/actions/python@master
-  #      env:
-  #        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-  #      with:
-  #        command: test
-  #        args: --all-projects --severity-threshold=high 
+
   sonarcloud:
-    needs: [Pylint, push-to-docker]
+    needs: [push-to-docker]
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-    - name: SonarCloud Scan
-      uses: SonarSource/sonarcloud-github-action@master
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - name: SonarCloud Scan
+        uses: SonarSource/sonarcloud-github-action@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
